INSERT INTO TEAM (NAME) VALUES ('PALMEIRAS');
INSERT INTO TEAM (NAME) VALUES ('CORINTHIANS');
INSERT INTO TEAM (NAME) VALUES ('FLAMENGO');
INSERT INTO TEAM (NAME) VALUES ('INTERNACIONAL');
INSERT INTO TEAM (NAME) VALUES ('VASCO');
INSERT INTO TEAM (NAME) VALUES ('GREMIO');
INSERT INTO TEAM (NAME) VALUES ('CRUZEIRO');
INSERT INTO TEAM (NAME) VALUES ('JUVENTUS');
